### PR TITLE
Upgrade React dependencies and add readonly prop

### PR DESCRIPTION
**Pull request by fedealconada**
- [x] Change react and react-dom versions to ^16.0.0
- [x] Import 'prop-types' from PropTypes
- [x] Add containerStyle via props
- [x] Add 'readonly' prop option (this is useful when you want to display tags not allowing the user to write more)

### CODE REVIEW

**Comment by peterp** [comment]
@fedealconada Thank you 🙇

**Comment by fedealconada** [comment]
:)

**Comment by peterp** [comment]
Hey @fedealconada, I ended up making a large amount of changes, but kept your suggestion for the readonly property.

Sorry that I didn't merge this.

**Comment by fedealconada** [comment]
Hey @peterp, no problem!

**Pull request closed without merging**
